package conexao.entity;
// Generated 30/10/2012 19:44:43 by Hibernate Tools 3.2.1.GA



/**
 * Areaatuacao generated by hbm2java
 */
public class AreaAtuacao  implements java.io.Serializable {


     private Long id;
     private String descricao;

    public AreaAtuacao() {
    }

    public AreaAtuacao(String descricao) {
       this.descricao = descricao;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


