package conexao.entity;
// Generated 30/10/2012 19:54:54 by Hibernate Tools 3.2.1.GA



/**
 * Universidade generated by hbm2java
 */
public class Universidade  implements java.io.Serializable {


     private Long id;
     private String nome;

    public Universidade() {
    }

    public Universidade(String nome) {
       this.nome = nome;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
}


